"""Full performance matrix for Havocforge — 29 cells + pregen fill rate.

Reconfigures the api container between rows (workers/cpus require recreate;
chaos can hot-reload via admin endpoint; metrics_enabled needs recreate). For
each cell runs httpx burst / single / WS stream benches and prints a markdown
table.

Designed to be run by the README's "Reproduce these numbers" section. Output
goes to stdout in markdown, with section dividers, so you can paste straight
into the README.
"""

from __future__ import annotations

import asyncio
import json
import statistics
import subprocess
import sys
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Any

import httpx
from websockets.asyncio.client import connect

REPO = Path(__file__).resolve().parent.parent.parent
ENV_FILE = REPO / ".env"
BENCH_OVERRIDE = REPO / "docker-compose.bench.yaml"
COMPOSE_FILE = REPO / "docker-compose.yaml"
CHAOS_YAML = REPO / "config" / "default" / "chaos.yaml"
SERVER_YAML = REPO / "config" / "default" / "server.yaml"

BASE = "http://localhost:8100"
WS_BASE = "ws://localhost:8100"


# ── Stack reconfig helpers ───────────────────────────────────────────────────


def _patch_env(workers: int) -> None:
    """Set WORKERS=N in .env."""
    txt = ENV_FILE.read_text()
    lines = []
    found = False
    for line in txt.splitlines():
        if line.startswith("WORKERS="):
            lines.append(f"WORKERS={workers}")
            found = True
        else:
            lines.append(line)
    if not found:
        lines.append(f"WORKERS={workers}")
    ENV_FILE.write_text("\n".join(lines) + "\n")


def _patch_bench_override(cpus: float, memory_gb: int = 2) -> None:
    """Re-write docker-compose.bench.yaml with the desired cpu+memory limits."""
    content = f"""# Bench override — generated by tests/perf/bench_matrix.py.
services:
  api:
    deploy:
      resources:
        limits:
          cpus: "{cpus}"
          memory: {memory_gb}g
    environment:
      - WORKERS=${{WORKERS:-1}}
    cpus: {cpus}
    mem_limit: {memory_gb}g

  generation-worker:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2g
    cpus: 1.0
    mem_limit: 2g
    environment:
      - GEN_WORKERS=1
"""
    BENCH_OVERRIDE.write_text(content)


def _patch_yaml_value(yaml_path: Path, key_path: list[str], value: str) -> None:
    """Surgical YAML value swap. Avoids dragging in PyYAML's round-trip cost."""
    txt = yaml_path.read_text()
    lines = txt.splitlines()
    # Find the deepest key's "value:" line under the nested path.
    indent = 0
    depth = 0
    for i, line in enumerate(lines):
        stripped = line.lstrip()
        cur_indent = len(line) - len(stripped)
        if depth < len(key_path) and stripped.startswith(key_path[depth] + ":"):
            if cur_indent >= indent:
                indent = cur_indent + 2
                depth += 1
                if depth == len(key_path):
                    # Next "value:" line under here is what we want
                    for j in range(i + 1, min(i + 8, len(lines))):
                        if lines[j].lstrip().startswith("value:"):
                            lead = lines[j][: len(lines[j]) - len(lines[j].lstrip())]
                            lines[j] = f"{lead}value: {value}"
                            yaml_path.write_text("\n".join(lines) + "\n")
                            return
    raise KeyError(f"could not find {' > '.join(key_path)} > value in {yaml_path}")


def _set_chaos_enabled(enabled: bool) -> None:
    _patch_yaml_value(CHAOS_YAML, ["chaos", "enabled"], "true" if enabled else "false")


def _set_metrics_enabled(enabled: bool) -> None:
    _patch_yaml_value(
        SERVER_YAML,
        ["server", "observability", "metrics_enabled"],
        "true" if enabled else "false",
    )


def _docker(*args: str, check: bool = True) -> str:
    cmd = ["docker", *args]
    r = subprocess.run(cmd, cwd=REPO, capture_output=True, text=True, check=check)
    return r.stdout.strip()


def _recreate_api() -> None:
    """Recreate the api container with current env + compose override."""
    subprocess.run(
        [
            "docker", "compose",
            "-f", str(COMPOSE_FILE),
            "-f", str(BENCH_OVERRIDE),
            "up", "-d", "--force-recreate", "api",
        ],
        cwd=REPO, capture_output=True, text=True, check=True,
    )


def _wait_api_ready(timeout_s: int = 180) -> None:
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        try:
            r = httpx.get(f"{BASE}/v1/health", timeout=2)
            if r.status_code == 200:
                return
        except httpx.RequestError:
            pass
        time.sleep(1)
    raise RuntimeError(f"api did not become ready in {timeout_s}s")


async def _hot_reload_chaos() -> None:
    async with httpx.AsyncClient(timeout=5) as c:
        await c.post(f"{BASE}/v1/admin/chaos/reload-config")


def _redis_llen(key: str) -> int:
    out = _docker("exec", "havocforge-redis", "redis-cli", "LLEN", key)
    return int(out or "0")


def _wait_pregen(min_items: int, key: str = "pregen:smoke:queue", timeout_s: int = 60) -> int:
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        n = _redis_llen(key)
        if n >= min_items:
            return n
        time.sleep(1)
    return _redis_llen(key)


# ── Bench primitives ─────────────────────────────────────────────────────────


async def bench_rest_burst(
    schema: str, count: int, concurrency: int, total: int
) -> dict[str, Any]:
    sem = asyncio.Semaphore(concurrency)
    latencies: list[float] = []
    statuses: list[int] = []

    async with httpx.AsyncClient(timeout=60) as client:
        async def one():
            async with sem:
                t = time.perf_counter()
                try:
                    r = await client.get(
                        f"{BASE}/v1/schemas/{schema}/generate",
                        params={"count": count, "persist": "false"},
                    )
                    latencies.append(time.perf_counter() - t)
                    statuses.append(r.status_code)
                except Exception:
                    latencies.append(time.perf_counter() - t)
                    statuses.append(0)

        t0 = time.perf_counter()
        await asyncio.gather(*[one() for _ in range(total)])
        wall = time.perf_counter() - t0

    ok = sum(1 for s in statuses if s == 200)
    non2xx = sum(1 for s in statuses if 200 < s < 600)
    failed = sum(1 for s in statuses if s == 0)
    items_total = ok * count
    sorted_l = sorted(latencies)
    return {
        "schema": schema, "count": count, "concurrency": concurrency,
        "requests": total, "ok": ok, "non2xx": non2xx, "failed": failed,
        "wall_s": round(wall, 3),
        "items_per_sec": int(items_total / wall) if wall > 0 else 0,
        "req_per_sec": round(total / wall, 1) if wall > 0 else 0,
        "p50_ms": round(statistics.median(latencies) * 1000, 1),
        "p95_ms": round(sorted_l[int(len(sorted_l) * 0.95)] * 1000, 1),
        "p99_ms": round(sorted_l[int(len(sorted_l) * 0.99)] * 1000, 1),
    }


async def bench_ws_stream(schema: str, max_events: int, pop_size: int) -> dict[str, Any]:
    uri = f"{WS_BASE}/v1/schemas/{schema}/stream?max_events={max_events}&count={pop_size}"
    received = 0
    first_t: float | None = None
    t0 = time.perf_counter()
    try:
        async with connect(uri, max_size=2**26) as ws:
            while True:
                try:
                    m = await asyncio.wait_for(ws.recv(), timeout=15)
                except asyncio.TimeoutError:
                    break
                msg = json.loads(m)
                if msg.get("type") == "event":
                    if first_t is None:
                        first_t = time.perf_counter()
                    received += 1
                elif msg.get("type") == "error":
                    break
    except Exception:
        pass
    wall = time.perf_counter() - t0
    sustained = received / (time.perf_counter() - first_t) if first_t else 0
    return {
        "schema": schema, "max_events": max_events, "pop_size": pop_size,
        "received": received, "wall_s": round(wall, 3),
        "items_per_sec": int(received / wall) if wall > 0 else 0,
        "items_per_sec_sustained": int(sustained),
    }


def bench_pregen_fill_rate(window_s: int = 60) -> dict[str, Any]:
    """Drain the smoke queue, then sample LLEN every second to compute fill rate."""
    _docker("exec", "havocforge-redis", "redis-cli", "DEL", "pregen:smoke:queue", check=False)
    time.sleep(1)
    samples: list[tuple[float, int]] = []
    t0 = time.time()
    while time.time() - t0 < window_s:
        n = _redis_llen("pregen:smoke:queue")
        samples.append((time.time() - t0, n))
        time.sleep(1)
    if len(samples) < 2:
        return {"window_s": window_s, "items_per_sec": 0, "final_size": 0}
    growth = samples[-1][1] - samples[0][1]
    elapsed = samples[-1][0] - samples[0][0]
    return {
        "window_s": window_s,
        "items_per_sec": int(growth / elapsed) if elapsed > 0 else 0,
        "final_size": samples[-1][1],
    }


# ── Output formatting ───────────────────────────────────────────────────────


def fmt_table(rows: list[dict[str, Any]], cols: list[str] | None = None) -> str:
    if not rows:
        return "(no rows)"
    if cols is None:
        cols = list(rows[0].keys())
    widths = [max(len(str(c)), max(len(str(r.get(c, ""))) for r in rows)) for c in cols]
    head = "| " + " | ".join(c.ljust(w) for c, w in zip(cols, widths)) + " |"
    sep = "| " + " | ".join("-" * w for w in widths) + " |"
    body = ["| " + " | ".join(str(r.get(c, "")).ljust(w) for c, w in zip(cols, widths)) + " |"
            for r in rows]
    return "\n".join([head, sep, *body])


# ── Orchestration ────────────────────────────────────────────────────────────


def reconfig(workers: int, chaos: bool, metrics: bool, requires_recreate: bool = True) -> None:
    """Apply a config and recreate api if needed. Waits for ready + pregen warmup."""
    if requires_recreate:
        _patch_env(workers)
        # ~2GB per worker — engine + faker need ~500MB each + headroom
        _patch_bench_override(cpus=float(workers), memory_gb=max(2, workers * 2))
        _set_chaos_enabled(chaos)
        _set_metrics_enabled(metrics)
        _recreate_api()
        _wait_api_ready()
    else:
        _set_chaos_enabled(chaos)
        asyncio.run(_hot_reload_chaos())


def _save_incremental(results: dict, label: str) -> None:
    """Flush partial results to disk so a mid-run failure doesn't lose data."""
    Path("/tmp/bench_results.json").write_text(json.dumps(results, indent=2, default=str))
    print(f"  ✓ saved partial: {label}", file=sys.stderr)


async def amain():
    results: dict[str, list[dict[str, Any]]] = {}

    # ── Matrix A: Worker scaling × batch size ───────────────────────────────
    # chaos=off, metrics=off, concurrency=50, smoke
    matrix_a: list[dict[str, Any]] = []
    for workers in (1, 2, 4, 8):
        print(f"# ── Matrix A: WORKERS={workers}, chaos=off, metrics=off ────────────────",
              file=sys.stderr)
        reconfig(workers=workers, chaos=False, metrics=False)
        _wait_pregen(min_items=5000)

        for batch, total, c in ((1, 500, 50), (10, 500, 50), (1000, 5, 1)):
            print(f"  → batch={batch} c={c} total={total}", file=sys.stderr)
            r = await bench_rest_burst("smoke", count=batch, concurrency=c, total=total)
            r["workers"] = workers
            r["batch"] = batch
            matrix_a.append(r)
            results["matrix_a"] = matrix_a
            _save_incremental(results, f"matrix_a W={workers} batch={batch}")

        # piggyback Matrix D (WS) for workers ∈ {1,2,4}
        if workers in (1, 2, 4):
            print(f"  → WS stream (max=20000, pop=500)", file=sys.stderr)
            _wait_pregen(min_items=15000)
            results.setdefault("matrix_d", []).append(
                {**(await bench_ws_stream("smoke", 20000, 500)), "workers": workers}
            )
            _save_incremental(results, f"matrix_d W={workers}")

        # piggyback Pregen fill rate at WORKERS=1
        if workers == 1:
            print(f"  → Pregen fill rate (60s, smoke queue)", file=sys.stderr)
            results["pregen_fill"] = [bench_pregen_fill_rate(60)]
            _save_incremental(results, "pregen_fill")

        # piggyback Matrix C (concurrency sweep) at WORKERS=4
        if workers == 4:
            print(f"  → Matrix C: concurrency sweep at WORKERS=4", file=sys.stderr)
            _wait_pregen(min_items=10000)
            matrix_c: list[dict[str, Any]] = []
            for c in (1, 5, 10, 50, 100, 200):
                r = await bench_rest_burst("smoke", count=10, concurrency=c, total=300)
                r["c"] = c
                matrix_c.append(r)
                results["matrix_c"] = matrix_c
                _save_incremental(results, f"matrix_c c={c}")

        # piggyback Matrix E (schemas) at WORKERS=4
        if workers == 4:
            print(f"  → Matrix E: schema complexity at WORKERS=4", file=sys.stderr)
            matrix_e: list[dict[str, Any]] = []
            for schema in ("smoke", "ga4", "patient", "stream_events"):
                r = await bench_rest_burst(schema, count=10, concurrency=50, total=200)
                r["schema_name"] = schema
                matrix_e.append(r)
                results["matrix_e"] = matrix_e
                _save_incremental(results, f"matrix_e schema={schema}")

    results["matrix_a"] = matrix_a

    # ── Matrix B: Feature cost matrix at WORKERS=1 ──────────────────────────
    # 4 cells: chaos × metrics
    matrix_b: list[dict[str, Any]] = []
    print("# ── Matrix B: chaos × metrics cost at WORKERS=1 ───────────────────────",
          file=sys.stderr)
    for chaos in (False, True):
        for metrics in (False, True):
            print(f"  → chaos={chaos} metrics={metrics}", file=sys.stderr)
            # metrics toggle requires recreate (middleware decided at app construction)
            reconfig(workers=1, chaos=chaos, metrics=metrics, requires_recreate=True)
            _wait_pregen(min_items=5000)
            r = await bench_rest_burst("smoke", count=10, concurrency=20, total=500)
            r["chaos"] = "on" if chaos else "off"
            r["metrics"] = "on" if metrics else "off"
            matrix_b.append(r)
            results["matrix_b"] = matrix_b
            _save_incremental(results, f"matrix_b chaos={chaos} metrics={metrics}")
    results["matrix_b"] = matrix_b

    # ── Print all results as markdown tables ────────────────────────────────
    print()
    print("# Performance — full matrix\n")

    print("## A. Worker scaling × batch size (chaos off, metrics off, c=50, smoke)\n")
    print(fmt_table(matrix_a, cols=[
        "workers", "batch", "concurrency", "ok", "items_per_sec",
        "req_per_sec", "p50_ms", "p95_ms", "p99_ms",
    ]))

    print("\n## B. Feature cost (WORKERS=1, smoke, batch=10, c=20, 500 reqs)\n")
    print(fmt_table(matrix_b, cols=[
        "chaos", "metrics", "ok", "non2xx", "items_per_sec",
        "req_per_sec", "p50_ms", "p95_ms", "p99_ms",
    ]))

    print("\n## C. Concurrency sweep (WORKERS=4, smoke, batch=10)\n")
    print(fmt_table(results["matrix_c"], cols=[
        "c", "ok", "items_per_sec", "req_per_sec",
        "p50_ms", "p95_ms", "p99_ms",
    ]))

    print("\n## D. WebSocket sustained throughput (smoke, max=20000, pop=500)\n")
    print(fmt_table(results["matrix_d"], cols=[
        "workers", "received", "wall_s",
        "items_per_sec", "items_per_sec_sustained",
    ]))

    print("\n## E. Schema complexity (WORKERS=4, batch=10, c=50, 200 reqs, chaos off)\n")
    print(fmt_table(results["matrix_e"], cols=[
        "schema_name", "ok", "items_per_sec",
        "req_per_sec", "p50_ms", "p95_ms", "p99_ms",
    ]))

    print("\n## F. Pre-generation worker fill rate (single worker, smoke)\n")
    print(fmt_table(results["pregen_fill"], cols=["window_s", "items_per_sec", "final_size"]))

    # Save raw JSON for later analysis
    Path("/tmp/bench_results.json").write_text(json.dumps(results, indent=2, default=str))
    print("\n_(raw results: /tmp/bench_results.json)_", file=sys.stderr)


if __name__ == "__main__":
    asyncio.run(amain())
